# Generated by Django 5.0.4 on 2024-05-07 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relation',
            field=models.ManyToManyField(related_name='rrelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
