# Generated by Django 5.0.4 on 2024-05-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relation_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='relation',
        ),
        migrations.AddField(
            model_name='relation',
            name='relation',
            field=models.BooleanField(default=False),
        ),
    ]
