# Generated by Django 5.0.4 on 2024-05-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_relation_relation_relation_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='relation',
            new_name='relat',
        ),
    ]
