# Generated by Django 5.0.4 on 2024-05-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_relation_relation_relat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='relat',
            new_name='relation',
        ),
    ]
