# Generated by Django 5.0.4 on 2024-05-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_relation_from_user_remove_relation_to_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='to_user',
        ),
        migrations.AddField(
            model_name='relation',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relation',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
