# Generated by Django 5.0.4 on 2024-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otpcode_code_alter_otpcode_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
