# Generated by Django 5.0.4 on 2024-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.BooleanField(default=False),
        ),
    ]
