# Generated by Django 5.0.4 on 2024-05-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comment_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='to_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='to_comment',
            field=models.ManyToManyField(blank=True, null=True, to='home.comment'),
        ),
    ]
