# Generated by Django 5.0.4 on 2024-05-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_comment_to_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcomment', to='home.comment'),
        ),
    ]
