# Generated by Django 5.0.4 on 2024-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_comment_replay_remove_comment_to_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.BooleanField(default=False),
        ),
    ]
