# Generated by Django 5.0.4 on 2024-05-09 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_comment_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replay',
        ),
        migrations.AlterField(
            model_name='commentreplay',
            name='to_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcomment', to='home.comment'),
        ),
    ]
